/*This is all element information for the box that'll appear on the side of the */
/*periodic table, all the repetetive numbers and words were generated by ChatGPT*/
let atomicNumArr = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
  60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
  79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
  98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
  114, 115, 116, 117, 118,
];

/*more info for the element info box on the side of the periodic table*/
let atomicMassArr = [
  0, 1.01, 4.0, 6.94, 9.01, 10.81, 12.01, 14.01, 16.0, 19.0, 20.18, 22.99,
  24.31, 26.98, 28.09, 30.97, 32.07, 35.45, 39.95, 39.1, 40.08, 44.96, 47.87,
  50.94, 52.0, 54.94, 55.85, 58.93, 58.69, 63.55, 65.38, 69.72, 72.63, 74.92,
  78.97, 79.9, 83.8, 85.47, 87.62, 88.91, 91.22, 92.91, 95.95, 98.0, 101.07,
  102.91, 106.42, 107.87, 112.41, 114.82, 118.71, 121.76, 127.6, 126.9, 131.29,
  132.91, 137.33, 138.91, 140.12, 140.91, 144.24, 145.0, 150.36, 151.96, 157.25,
  158.93, 162.5, 164.93, 167.26, 168.93, 173.05, 174.97, 178.49, 180.95, 183.84,
  186.21, 190.23, 192.22, 195.08, 196.97, 200.59, 204.38, 207.2, 208.98, 209.0,
  210.0, 222.0, 223.0, 226.0, 227.0, 232.04, 231.04, 238.03, 237.0, 244.0,
  243.0, 247.0, 247.0, 251.0, 252.0, 257.0, 258.0, 259.0, 262.0, 267.0, 268.0,
  269.0, 270.0, 269.0, 278.0, 281.0, 282.0, 285.0, 286.0, 289.0, 290.0, 293.0,
  294.0, 294.0,
];

/*more info for the element info box on side of periodic table*/
let elementNamesArr = ["","Hydrogen","Helium","Lithium","Beryllium","Boron","Carbon",
  "Nitrogen","Oxygen","Fluorine","Neon","Sodium","Magnesium","Aluminum","Silicon",
  "Phosphorus","Sulfur","Chlorine","Argon","Potassium","Calcium","Scandium","Titanium",
  "Vanadium","Chromium","Manganese","Iron","Cobalt","Nickel","Copper","Zinc","Gallium",
  "Germanium","Arsenic","Selenium","Bromine","Krypton","Rubidium","Strontium","Yttrium",
  "Zirconium","Niobium","Molybdenum","Technetium","Ruthenium","Rhodium","Palladium",
  "Silver","Cadmium","Indium","Tin","Antimony","Tellurium","Iodine","Xenon","Cesium",
  "Barium","Lanthanum","Cerium","Praseodymium","Neodymium","Promethium","Samarium",
  "Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium",
  "Lutetium","Hafnium","Tantalum","Tungsten","Rhenium","Osmium","Iridium","Platinum",
  "Gold","Mercury","Thallium","Lead","Bismuth","Polonium","Astatine","Radon","Francium",
  "Radium","Actinium","Thorium","Protactinium","Uranium","Neptunium","Plutonium","Americium",
  "Curium","Berkelium","Californium","Einsteinium","Fermium","Mendelevium","Nobelium",
  "Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium",
  "Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium","Livermorium","Tennessine","Oganesson",
];

/*more info, some boiling points are unknown so I've added those in too*/
let boilingPointArr = [0,-252.87,-268.93,1330,2469,3927,4027,-195.79,-182.96,-188.11, -246.05, 882.94, 1090,
  2470, 3265, 277, 444.6, -34.04, -185.85, 759, 1484, 2836, 3287, 3402, 2671, 2061, 2900, 2477, 3570, 2830, 2970,
  2860,2632,1757,3464,3443, 3290, 3081, 3027, 2742, 2390, 2470, 2400, 2437, 2865, 2980, 3639, 3930, 3695, 2963, 
  2162, 767, 1180,1650,1837,1857,1650,1655,3370,3040,3127,2330, "unknown",1750,1090, 1090,2680, 2730,2868,2293,3345,4100,4090,
  4130,3850,3227,2607,3110,2896, 3464, 4788, 4027,3200, 2875,5470, 659.3, 1749,3464, 3413, 4130,"unknown",3020, 3680,"unknown", "unknown",
  "unknown","unknown","unknown","unknown","unknown","unknown","unknown","unknown","unknown","unknown","unknown","unknown",
];

/*switches pages for the user*/
function goToNextPage(nextPage) {
  window.location.href = nextPage;
  let nameInput = document.querySelector("#name");
  localStorage.setItem("name", nameInput.value);
}

/*makes the box on the side w/ all the information. This is sent to the html to actually be made*/
function showElementInfo(num) {
  if (!elementNamesArr[num]) {
    /*error message in case the number can't be found. No such error has appeared so far*/
    document.getElementById("element-info-box").innerHTML =
      "Element data not found.";
  }
  let atomicNum =
    atomicNumArr[
      num
    ]; /*taking the information from the arrays w/ their respective atomic number that was sent through the html*/
  let atomicMass = atomicMassArr[num];
  let elementName = elementNamesArr[num];
  let boilingPoint = boilingPointArr[num];
  document.getElementById("element-info-box").innerHTML =
    elementName +
    "<br>" +
 "<br>" /*passing the information to the html file*/ + "Atomic number: " + atomicNum +
    "<br>" + "<br>" + "Atomic mass: " + atomicMass + " amu" + "<br>" + "<br>" + "Boiling point: " + boilingPoint + "°C";
}

/*actions for atomic radius button*/
document.getElementById("atomic-radius").addEventListener("click", function () {
  const imgBox = document.getElementById("trend-images");
  // Clear any previous images
  imgBox.innerHTML = "";
  // Add the new images, they were made on Canva
  imgBox.innerHTML = `
        <img src="AR_Across.png" alt="Atomic Radius Across"> 
        <img src="AR_Down.png" alt="Atomic Radius Down">
    `;
});

/*actions for the electronegativity button*/
document
  .getElementById("electronegativity")
  .addEventListener("click", function () {
    const imgBox = document.getElementById("trend-images");
    // Clear any previous images
    imgBox.innerHTML = "";
    // Add the new images which were made with Canva
    imgBox.innerHTML = `
        <img src="EN+IE_Across.png" alt="Electronegativity Across">
        <img src="EN+IE_Down.png" alt="Electronegativity Down">
    `;
  });

/*actions for the ionization energy button*/
document
  .getElementById("ionization-energy")
  .addEventListener("click", function () {
    const imgBox = document.getElementById("trend-images");
    // Clear any previous images
    imgBox.innerHTML = "";
    // Add the new images, made with Canva
    imgBox.innerHTML = `
        <img src="EN+IE_Across.png" alt="Ionization Energy Across">
        <img src="EN+IE_Down.png" alt="Ionization Energy Down">
    `;
  });
